version: '3.8'
services:
    dev-db:
        image: postgres:13
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: ecommerce
        ports:
            - 5435:5432
        networks:
            - ecommerce-network
networks:
    ecommerce-network:
        driver: bridge